export { AuthLoginPage } from "./auth-login.page";
export { AuthRegisterPage } from "./auth-register.page";
export { CakePage } from "./cake.page";
export { ChildrensMenuPage } from "./child-food.page";
export { FastFoodPage } from "./fast-food.page";
export { HomePage } from "./home.page";
export { MainCoursePage } from "./main-course.page";
export { SoupPage } from "./soup.page";
export { VegetarianPage } from "./vegetarian.page";
